language: ruby

rvm:
  - 2.1.2
  - 1.9.3

branches:
  only:
    - "master"

before_install:
  - sudo apt-get update
  - export PATH=$PATH:/usr/games

install:
  - sudo apt-get install cowsay fortune

script:
  - make test-report

addons:
  code_climate:
    repo_token: ea9f143077246776b08ea6cb17e7a1480f20c10bc05701c2d5ffa87cec888aa6
