branches:
  only:
    - "master"

before_install:
  - sudo apt-get update
  - sudo apt-get install cowsay
  - sudo apt-get install fortune-mod
  - which fortune
  - which cowsay

script:
  - make test
